apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: welcome-app
  labels:
    app: backend
    version: "1.0"
    auth: enabled
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        version: "1.0"
        auth: enabled
    spec:
      containers:
      - name: backend
        image: atoy3731/welcome-app-backend:1.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_HOST
          value: "mongo.welcome-app.svc.cluster.local"
        - name: MONGODB_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: welcome-app
  labels:
    auth: enabled
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000