apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: welcome-app
  labels:
    app: ui
    version: "1.4"
    auth: enabled
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
        version: "1.4"
        auth: enabled
        
    spec:
      containers:
      - name: ui
        image: atoy3731/welcome-app-ui:1.7
        ports:
        - containerPort: 80
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: welcome-app
  labels:
    auth: enabled
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
