apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: authservice
  namespace: authservice
stringData: 
  config.json: |
    {
    "listen_address": "0.0.0.0",
    "listen_port": "10003",
    "log_level": "trace",
    "threads": 8,
    "chains": [
        {
        "name": "welcome-app",
        "match": {
            "header": ":authority",
            "prefix": "welcome-istiocon.atoy.lol"
        },
        "filters": [
            {
            "oidc": {
                "authorization_uri": "http://keycloak-istiocon.atoy.lol/auth/realms/demo/protocol/openid-connect/auth",
                "token_uri": "http://keycloak-istiocon.atoy.lol/auth/realms/demo/protocol/openid-connect/token",
                "callback_uri": "http://welcome-istiocon.atoy.lol/oauth/callback",
                "jwks": "{\"keys\":[{\"kid\":\"7iWaczINKc3VagVNTAFc7LVqYqMltBcAbUkQvzvnMc4\",\"kty\":\"RSA\",\"alg\":\"RS256\",\"use\":\"sig\",\"n\":\"w89sCBR_bNjCrIv4isry0u1RMsZIK57TupPQsRENh17ig1GC5u2gYkyvTFH4jOQ0tQLDjZyyiFbZZSHDYKha42L85EJrs3oS6M5_Ox1Od1gTHVUqHU8AEhnYLbzevhMd1BrlHaBRohBn1_Ceimr959j9UoQzYXWCikIy_hclW2z6Lpn1uD3Ns33k_wzdOWv6reTtOJngg_uR3WIMbv2jbKDz5o6NDlgWsYb4OKmOop4Riec-LFwdZaripEs0JufHHrBUbIt1dAMXWU4211cxA70zb17UtQr8mwph_OJY6wj6COSDAL9qh5KgdvUX7EQbdooOy_u5AQpR36ms9n7J4w\",\"e\":\"AQAB\",\"x5c\":[\"MIIClzCCAX8CBgF3sPaNXzANBgkqhkiG9w0BAQsFADAPMQ0wCwYDVQQDDARkZW1vMB4XDTIxMDIxNzE3MDYyNFoXDTMxMDIxNzE3MDgwNFowDzENMAsGA1UEAwwEZGVtbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMPPbAgUf2zYwqyL+IrK8tLtUTLGSCue07qT0LERDYde4oNRgubtoGJMr0xR+IzkNLUCw42csohW2WUhw2CoWuNi/ORCa7N6EujOfzsdTndYEx1VKh1PABIZ2C283r4THdQa5R2gUaIQZ9fwnopq/efY/VKEM2F1gopCMv4XJVts+i6Z9bg9zbN95P8M3Tlr+q3k7TiZ4IP7kd1iDG79o2yg8+aOjQ5YFrGG+DipjqKeEYnnPixcHWWq4qRLNCbnxx6wVGyLdXQDF1lONtdXMQO9M29e1LUK/JsKYfziWOsI+gjkgwC/aoeSoHb1F+xEG3aKDsv7uQEKUd+prPZ+yeMCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAvLK91RKkoi8o23pMCfnmnBupJRW6wD0JKaoH3Tpe+I2opUbDPJrTzkLx5OQQ8VbaBeJBma2Nd97qN5RGBqxBO9+UNkMocOUtb2m93eT4vPewRUyPTp7xof/NTvuWiYKT3F0jrcQhG8YFfErMy1eWv79nXJti+zePQ8oG8c969LkPM2wj3s30f7HqSjCRl1oaXTxsSbFw8+ODp/e4voTxnLOagwZ4b+zzJpvjacQZd9xHX8wA436l5ulwBhGDtFJs8P+iwMf8y6NjtwkPvaeDBNNAVQVJT3/lFD/OM+L/ieiArbKp3tMsIFfeEYneIkYTZyMxFQzuKsCaRuoitA4vEA==\"],\"x5t\":\"RrAdRjwv4j6Vo4xZuUbO_EwvseM\",\"x5t#S256\":\"4as-aPl5Vz6tsoem1mxlPJ66rw347s2fS4Dg2zrwv7U\"}]}",
                "client_id": "welcome-client",
                "client_secret": "c882c331-87c2-499f-894b-65b78b9ab600",
                "scopes": [],
                "cookie_name_prefix": "welcome-app",
                "id_token": {
                "preamble": "Bearer",
                "header": "Authorization"
                },
                "access_token": {
                "header": "JWT"
                },
                "trusted_certificate_authority": "",
                "logout": {
                "path": "/oauth/logout",
                "redirect_uri": "http://keycloak-istiocon.atoy.lol/auth/realms/demo/protocol/openid-connect/token/logout"
                }
            }
            }
        ]
        }
    ]
    }