apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: main
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway 
  servers:
  - hosts:
    - "*"
    port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - '*.atoy.lol'
    port:
      name: https-atoy-lol
      number: 443
      protocol: HTTPS
    tls:
      credentialName: atoy-lol-ingress
      mode: SIMPLE   
