hostname: atoy.lol

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

clusterAuditor:
  enabled: false

gatekeeper:
  values:
    replicas: 1

istio:
  values:
    tls:
      credentialName: main-cert
    kiali:
      dashboard:
        auth:
          strategy: anonymous

logging:
  enabled: false

monitoring:
  enabled: true

twistlock:
  enabled: false
  values:
    console:
      persistence:
        size: 5Gi

addons:
  authservice:
    git:
      tag: "0.1.6-bb.2"
    enabled: true
    values:
      replicaCount: 1

      image:
        repository: registry.dsop.io/platform-one/big-bang/apps/sandbox/authservice

      selector:
        key: auth
        value: enabled