# When updating the version of BigBang, make sure to update
#   both the bases reference and the GitRepository reference
bases:
- https://repo1.dsop.io/platform-one/big-bang/umbrella.git//base?ref=1.0.6
resources:
- ingress-cert.enc.yaml
configMapGenerator:
  - name: common
    behavior: merge
    files:
      - values.yaml=configmap.yaml
patchesStrategicMerge:
- secrets.enc.yaml
- |-
  apiVersion: source.toolkit.fluxcd.io/v1beta1
  kind: GitRepository
  metadata:
    name: bigbang
  spec:
    ref:
      $patch: replace
      semver: "1.0.6"